name: Run tests with pytest

on:
  push:
    paths-ignore:
      - '*.rst'
  pull_request:
    paths-ignore:
      - '*.rst'
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.x']
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the package
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run tests with pytest
        run: |
          pip install pytest
          pytest tests
